env:
  - FLASK_APP=cusg CUSG_ENV=test LOG_LEVEL=ERROR CUSG_SECRET=oh-so-secret CUSG_DEBUG=YES
services:
  - postgresql
language: python
python:
  - "3.8"
install:
  - pip install -r req-dev.txt
script:
  - psql -c "CREATE DATABASE ${CUSG_ENV}" -U postgres
  - python manage.py db upgrade
  - python -m pytest -v --log-cli-level=${LOG_LEVEL}
