env:
  - CUSG_TESTING=YES CUSG_DEBUG=YES
services:
  - postgresql
language: python
install:
  - python -m pip install pipenv
  - pipenv sync
script:
  - psql -c 'create database cusg_test_db;' -U postgres
  - flask db upgrade
  - pipenv run python setup_defaults.py
  - pipenv run python -m pytest -v --log-cli-level=DEBUG
