env:
  - DB_NAME=cusg_db_testing LOG_LEVEL=ERROR CUSG_SECRET=oh-so-secret CUSG_DEBUG=YES CUSG_DB_CONNETION_STRING=postgresql://postgres:postgres@localhost:5432/${DB_NAME}
services:
  - postgresql
language: python
python:
  - "3.8"
install:
  - pip install -r req-dev.txt
script:
  - psql -c "CREATE DATABASE ${DB_NAME}" -U postgres
  - flask db upgrade
  - python setup_defaults.py
  - python -m pytest -v --log-cli-level=${LOG_LEVEL}
