version: "3"
services:
  db:
    container_name: cusg-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=cusg_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - v-postgres:/var/lib/postgresql/data
    networks:
      - cusg
  server:
    container_name: cusg-server
    image: critical-usg-backend:${CUSG_VERSION:-latest}
    restart: always
    depends_on:
      - db
    build:
      context: .
    environment:
      CUSG_GUNICORN_WORKERS: ${CUSG_GUNICORN_WORKERS:-2}
      CUSG_ENV: ${CUSG_ENV:-prod}
      CUSG_SECRET: ${CUSG_SECRET}
      FLASK_ENV: ${FLASK_ENV:-production}
      FLASK_DEBUG: ${FLASK_DEBUG:-0}
    expose: 
      - 8000
    volumes:
    - v-files:/opt/app/cusg/files
    - v-server-logs:/opt/app/logs
    networks:
      - cusg
  nginx:
    depends_on: 
      - server
    image: nginx
    restart: always
    container_name: cusg-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - v-files:/media:ro
    ports:
      - ${CUSG_PORT-9001}:80
    networks:
      - cusg
volumes:
  v-postgres:
  v-files:
  v-server-logs:
networks:
  cusg:
