version: "3"
services:
  db:
    container_name: cusg-postgres-${CUSG_ENV:-prod}
    image: postgres
    environment:
      - POSTGRES_DB=cusg_db_${CUSG_ENV:-prod}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cusg_network
  cusg:
    container_name: cusg-server-${CUSG_ENV:-prod}
    depends_on:
      - db
    build:
      context: .
    image: critical-usg-backend:${CUSG_VERSION:-latest}
    environment:
      CUSG_GUNICORN_WORKERS: ${CUSG_GUNICORN_WORKERS:-2}
      CUSG_ENV: ${CUSG_ENV:-prod}
      CUSG_SECRET: ${CUSG_SECRET}
      FLASK_APP: cusg:app
      FLASK_ENV: ${FLASK_ENV:-production}
      FLASK_DEBUG: ${FLASK_DEBUG:-1}
    expose: 
      - 8000
    volumes:
    - cusg-files:/opt/app/cusg/files/api/filez
    - cusg-server-logs:/opt/app/logs
    networks:
      - cusg_network

  nginx:
    depends_on: 
      - cusg
    image: nginx:latest
    container_name: cusg-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9001:80
    networks:
      - cusg_network

volumes:
  postgres-data:
  cusg-files:
  cusg-server-logs:
networks:
  cusg_network:
