version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB="cusg_db_${CUSG_ENV:-prod}"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cusg_network
  cusg:
    depends_on:
      - db
    build:
      context: .
    image: critical-usg-backend:${CUSG_VERSION:-latest}
    ports:
      - "${CUSG_PORT-9001}:80"
    environment:
      CUSG_GUNICORN_WORKERS: ${CUSG_GUNICORN_WORKERS:-2}
      CUSG_SECRET: "${CUSG_SECRET}"
      CUSG_DEBUG: "${CUSG_DEBUG:-NO}"
      FLASK_APP: "cusg"
      CUSG_ENV: "${CUSG_ENV:-prod}"
    volumes:
    - cusg-files:/opt/app/cusg/files/api/filez
    networks:
      - cusg_network

volumes:
  postgres-data:
  cusg-files:
networks:
  cusg_network:
