"""cascade

Revision ID: 9136efebc74b
Revises: 45eb056265bf
Create Date: 2020-07-04 11:40:38.089936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9136efebc74b'
down_revision = '45eb056265bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('instruction_document_page_document_id_fkey', 'instruction_document_page', type_='foreignkey')
    op.create_foreign_key(None, 'instruction_document_page', 'instruction_document', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instruction_document_page', type_='foreignkey')
    op.create_foreign_key('instruction_document_page_document_id_fkey', 'instruction_document_page', 'instruction_document', ['document_id'], ['id'])
    # ### end Alembic commands ###
