"""empty message

Revision ID: b8f364b14e8c
Revises: 408ab690a4ae
Create Date: 2020-08-09 16:56:10.976831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f364b14e8c'
down_revision = '408ab690a4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruction_document', sa.Column('slug', sa.String(length=400), nullable=False))
    op.create_index(op.f('ix_instruction_document_slug'), 'instruction_document', ['slug'], unique=False)
    op.create_unique_constraint(None, 'instruction_document', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instruction_document', type_='unique')
    op.drop_index(op.f('ix_instruction_document_slug'), table_name='instruction_document')
    op.drop_column('instruction_document', 'slug')
    # ### end Alembic commands ###
