"""empty message

Revision ID: c925285c7470
Revises: b8f364b14e8c
Create Date: 2020-08-09 17:18:20.745823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c925285c7470'
down_revision = 'b8f364b14e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_instruction_document_slug', table_name='instruction_document')
    op.create_index(op.f('ix_instruction_document_slug'), 'instruction_document', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruction_document_slug'), table_name='instruction_document')
    op.create_index('ix_instruction_document_slug', 'instruction_document', ['slug'], unique=False)
    # ### end Alembic commands ###
