"""empty message

Revision ID: ee2d45443c83
Revises: 36a1246d5574
Create Date: 2020-08-05 21:41:41.535487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee2d45443c83'
down_revision = '36a1246d5574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruction_document_page', sa.Column('md', sa.Text(), nullable=True))
    op.drop_column('instruction_document_page', 'json_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruction_document_page', sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('instruction_document_page', 'md')
    # ### end Alembic commands ###
