"""user is deleted attr

Revision ID: 21aa04634b48
Revises: c4e28b6f4532
Create Date: 2020-06-21 10:35:39.145757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aa04634b48'
down_revision = 'c4e28b6f4532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###
